import { Hono } from 'hono';
import { jwt } from 'hono/jwt';
import { drizzle } from 'drizzle-orm/d1';
import { eq, inArray } from 'drizzle-orm';
import { vocabulary, questions as questionsTable, users } from '../../db/schema';
import { sql } from 'drizzle-orm';
import type { Bindings } from '../../index';
import { AIService } from '../../services/ai.service';
import { requireJwtSecret } from '../../middleware/auth';

const aiRouter = new Hono<{ Bindings: Bindings }>();
const JSON_CHAT_MODEL = '@cf/meta/llama-3.3-70b-instruct-fp8-fast';

// Auth middleware
aiRouter.use('/*', async (c, next) => {
  const secret = requireJwtSecret(c);
  return jwt({ secret, alg: 'HS256' })(c, next);
});

/**
 * POST /api/v1/ai/pronunciation-check
 * Body: { audio: base64, target_text: string }
 */
aiRouter.post('/pronunciation-check', async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const { audio, target_text, only_transcript } = body;

  if (!audio || !target_text) {
    return c.json({ success: false, message: 'Missing audio or target_text' }, 422);
  }

  const db = drizzle(c.env.DB);
  const userPayload = c.get('jwtPayload') as { id?: string } | undefined;
  let shouldDeductCoins = false;

  try {
    if (userPayload?.id) {
      // Check user coins
      const user = await db.select().from(users).where(eq(users.id, userPayload.id)).get();
      if (!user || (user.coins ?? 0) < 4) {
        return c.json({ success: false, error: { code: 'INSUFFICIENT_CREDITS', message: 'Bạn cần ít nhất 4 Xu để sử dụng tính năng này.' } }, 402);
      }
      shouldDeductCoins = true;
    }
    // 1. Chuyển base64 sang Uint8Array
    const binaryString = atob(audio);
    const audioBuffer = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      audioBuffer[i] = binaryString.charCodeAt(i);
    }

    // 2. Sử dụng Cloudflare Workers AI Whisper để lấy Transcription (Latin)
    const response = await c.env.AI.run('@cf/openai/whisper', {
      audio: [...audioBuffer],
      language: "en"
    });

    const transcription = response.text?.trim() || '';

    // Nếu client chỉ yêu cầu transcript (để tự chấm điểm offline)
    if (only_transcript) {
      return c.json({
        success: true,
        data: {
          transcription: transcription
        }
      });
    }

    const cleanTarget = target_text.trim().toLowerCase().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g,"");
    const cleanHeard = transcription.toLowerCase().replace(/[.,\/#!$%\^&\*;:{}=\-_`~()]/g,"");
    const targetWords = cleanTarget.split(/\s+/).filter(Boolean);
    const heardWords = cleanHeard.split(/\s+/).filter(Boolean);
    const isEnglishToken = (word: string) => /^[a-z]+(?:'[a-z]+)?$/i.test(word);

    // 3. Chuyển đổi sang IPA để chấm điểm chính xác hơn
    // Hàm lấy IPA (có AI fallback)
    const getIpaForWords = async (words: string[]) => {
      if (words.length === 0) return new Map<string, string>();
      
      // 1. Tra cứu từ DB trước
      const foundVocabs = await db.select({ 
        word: vocabulary.word,
        pronunciation: vocabulary.pronunciation 
      })
        .from(vocabulary)
        .where(inArray(vocabulary.word, words))
        .all();
      
      const vocabMap = new Map(foundVocabs.map(v => [v.word, v.pronunciation]));
      const missingWords = words.filter(w => !vocabMap.has(w) && isEnglishToken(w));
      words
        .filter(w => !isEnglishToken(w))
        .forEach(w => vocabMap.set(w, `/${w}/`));

      // 2. Nếu thiếu, dùng AI để suy luận IPA
      if (missingWords.length > 0) {
        console.log(`[AI IPA] Missing ${missingWords.length} words, generating via AI:`, missingWords);
        try {
          const prompt = `Generate standard International Phonetic Alphabet (IPA) for these English words. Return ONLY a JSON object where keys are words and values are IPA strings (enclosed in slashes / /).
Words: ${missingWords.join(', ')}`;

          const aiRes = await c.env.AI.run(JSON_CHAT_MODEL, {
            messages: [{ role: 'user', content: prompt }],
            response_format: { type: 'json_object' }
          });

          const generatedIpas = JSON.parse(aiRes.response);
          
          // 3. Lưu vào DB để lần sau dùng luôn (Async - không đợi để tối ưu tốc độ phản hồi)
          for (const [word, ipa] of Object.entries(generatedIpas)) {
            const cleanIpa = String(ipa);
            const now = Math.floor(Date.now() / 1000);
            vocabMap.set(word, cleanIpa);
            
            // Upsert vào DB (D1)
            c.executionCtx.waitUntil(
              db.insert(vocabulary)
                .values({ 
                  word: String(word),
                  pronunciation: cleanIpa,
                  definition: 'Auto-generated by AI',
                  topic: 'AI-Generated',
                  status: 'published',
                  updated_at: now,
                  is_deleted: 0
                })
                .onConflictDoUpdate({
                  target: vocabulary.word,
                  set: { pronunciation: cleanIpa, updated_at: now }
                })
                .execute()
                .catch((cacheErr) => {
                  console.error('[AI IPA Cache Error]', cacheErr);
                })
            );
          }
        } catch (err) {
          console.error('[AI IPA Error]', err);
          // Fallback: dùng chính text thô nếu AI lỗi
          missingWords.forEach(w => vocabMap.set(w, `/${w}/`));
        }
      }
      return vocabMap;
    };

    // Lấy IPA cho Target và Heard
    const allWordsToFetch = Array.from(new Set([...targetWords, ...heardWords]));
    const fullVocabMap = await getIpaForWords(allWordsToFetch);

    const targetIpa = targetWords.map((w: string) => fullVocabMap.get(w) || `/${w}/`).join(' ');
    const heardIpa = heardWords.map((w: string) => fullVocabMap.get(w) || `/${w}/`).join(' ');

    // CHIẾN LƯỢC CHẤM ĐIỂM MỚI:
    const normalizeForComparison = (s: string) => {
      let res = s.toLowerCase()
        .replace(/[\/\u02c8\u02cc\[\]]/g, '') // Bỏ slash, trọng âm, ngoặc vuông
        .replace(/\s/g, '');                  // Bỏ khoảng trắng
      
      // Bản đồ chuyển đổi các âm tương đồng (Phonetic Mapping)
      const phoneticMap: Record<string, string> = {
        'ɪ': 'i', 'iː': 'i', 'i': 'i',
        'ɛ': 'e', 'æ': 'e', 'e': 'e',
        'ə': 'a', 'ʌ': 'a', 'ɑː': 'a', 'a': 'a',
        'ʊ': 'u', 'uː': 'u', 'ʉː': 'u', 'u': 'u',
        'ɔː': 'o', 'ɒ': 'o', 'o': 'o',
        's': 's', 'z': 's', 'ʃ': 's', 'ʒ': 's',
        'f': 'f', 'v': 'f',
        't': 't', 'd': 't',
        'k': 'k', 'g': 'k',
        'p': 'p', 'b': 'p',
      };

      Object.entries(phoneticMap).forEach(([key, value]) => {
        const regex = new RegExp(key, 'g');
        res = res.replace(regex, value);
      });

      return res.replace(/[^a-z0-9]/g, '').trim();
    };

    let accuracy = 0;
    const normTarget = normalizeForComparison(targetIpa);
    const normHeard = normalizeForComparison(heardIpa);

    if (normTarget && normHeard) {
      accuracy = calculateAccuracy(normTarget, normHeard);
      
      // Bonus 3: Xử lý Homophones hoặc nghe gần giống
      if (accuracy < 0.8) {
        // Substring match: Chỉ tính nếu normHeard có độ dài đáng kể
        if (normHeard.length >= 2 && (normHeard.includes(normTarget) || normTarget.includes(normHeard))) {
          accuracy = Math.max(accuracy, 0.8);
        }
        
        const dist = calculateAccuracy(normTarget, normHeard);
        if (dist > 0.6) {
           accuracy = Math.max(accuracy, dist + 0.1);
        }
      }
    } else {
      // Fallback: So sánh text thô nếu không có IPA (nhưng vẫn phải có text)
      if (cleanTarget && cleanHeard) {
        accuracy = calculateAccuracy(cleanTarget, cleanHeard);
      }
    }

    // Giới hạn accuracy tối đa 1.0
    accuracy = Math.min(1.0, accuracy);

    // Bonus: Nếu text thô giống hệt nhau, accuracy là 1
    if (cleanTarget === cleanHeard) accuracy = 1.0;
    
    // Bonus 2: Nếu từ mục tiêu xuất hiện trong chuỗi nghe được (vd: target "apple", heard "an apple")
    if (cleanHeard.includes(cleanTarget) && accuracy < 0.8) {
      accuracy = Math.max(accuracy, 0.85);
    }

    if (shouldDeductCoins && userPayload?.id) {
      await db.update(users).set({ coins: sql`${users.coins} - 4` }).where(eq(users.id, userPayload.id)).execute();
    }

    return c.json({
      success: true,
      data: {
        transcription: cleanHeard,
        target_text: cleanTarget,
        target_ipa: targetIpa,
        heard_ipa: heardIpa,
        accuracy,
        status: accuracy >= 0.8 ? 'excellent' : accuracy >= 0.5 ? 'good' : 'try_again'
      }
    });
  } catch (error: any) {
    console.error('AI Pronunciation Error:', error);
    return c.json({ success: false, message: 'AI processing failed', error: error.message }, 500);
  }
});

/**
 * POST /api/v1/ai/explain
 * Body: { question_id, passage?, question?, options?, correct_answer? }
 */
aiRouter.post('/explain', async (c) => {
  const { question_id, passage, question, options, correct_answer } = await c.req.json();

  if (!question_id && (!passage || !question || !correct_answer)) {
    return c.json({ success: false, message: 'Missing required fields' }, 422);
  }

  const db = drizzle(c.env.DB);
  const aiService = new AIService(c.env.AI, c.env.CACHE);

  try {
    let finalPassage = passage;
    let finalQuestion = question;
    let finalOptions = options || [];
    let finalCorrectAnswer = correct_answer;

    // Nếu có question_id, ưu tiên lấy từ DB để đảm bảo data chuẩn
    if (question_id) {
      const q = await db.select().from(questionsTable).where(eq(questionsTable.id, question_id)).get();
      if (q) {
        finalQuestion = q.content;
        finalCorrectAnswer = q.correct_answer;
        finalOptions = q.options ? (typeof q.options === 'string' ? JSON.parse(q.options) : q.options) : [];
        
        // Fetch passage via group
        const { questionGroups, passages } = await import('../../db/schema');
        if (q.group_id) {
          const group = await db.select().from(questionGroups).where(eq(questionGroups.id, q.group_id)).get();
          if (group?.passage_id) {
            const p = await db.select().from(passages).where(eq(passages.id, group.passage_id)).get();
            if (p) finalPassage = p.content_html;
          }
        }
      }
    }

    const result = await aiService.generateExplanation(
      finalPassage || '',
      finalQuestion || '',
      Array.isArray(finalOptions) ? finalOptions : [],
      finalCorrectAnswer || '',
      question_id
    );

    return c.json({ success: true, data: result });
  } catch (error: any) {
    console.error('AI Explain Error:', error);
    return c.json({ success: false, message: 'AI processing failed' }, 500);
  }
});

/**
 * POST /api/v1/ai/explain/batch
 * Body: { questions: [{ question_id, passage?, question?, options?, correct_answer? }] }
 */
aiRouter.post('/explain/batch', async (c) => {
  const { questions: items } = await c.req.json();

  if (!Array.isArray(items)) {
    return c.json({ success: false, message: 'Invalid questions array' }, 422);
  }

  const db = drizzle(c.env.DB);
  const aiService = new AIService(c.env.AI, c.env.CACHE);
  
  // 1. Lấy toàn bộ data từ DB trước nếu cần
  const questionIds = items.map(i => i.question_id).filter(id => !!id);
  let dbQuestions: any[] = [];
  if (questionIds.length > 0) {
    const { questions: qTable } = await import('../../db/schema');
    const { inArray } = await import('drizzle-orm');
    dbQuestions = await db.select().from(qTable).where(inArray(qTable.id, questionIds)).all();
  }

  // 2. Xử lý từng câu (có cache lo liệu bên trong AIService)
  const results = await Promise.all(items.map(async (item) => {
    let finalPassage = item.passage;
    let finalQuestion = item.question;
    let finalOptions = item.options || [];
    let finalCorrectAnswer = item.correct_answer;

    if (item.question_id) {
      const q = dbQuestions.find(dq => dq.id === item.question_id);
      if (q) {
        finalQuestion = q.content;
        finalCorrectAnswer = q.correct_answer;
        finalOptions = q.options ? (typeof q.options === 'string' ? JSON.parse(q.options) : q.options) : [];
        
        // Fetch passage if missing
        if (!finalPassage && q.group_id) {
          const { questionGroups, passages } = await import('../../db/schema');
          const group = await db.select().from(questionGroups).where(eq(questionGroups.id, q.group_id)).get();
          if (group?.passage_id) {
            const p = await db.select().from(passages).where(eq(passages.id, group.passage_id)).get();
            if (p) finalPassage = p.content_html;
          }
        }
      }
    }

    try {
      return {
        question_id: item.question_id,
        ...(await aiService.generateExplanation(
          finalPassage || '',
          finalQuestion || '',
          Array.isArray(finalOptions) ? finalOptions : [],
          finalCorrectAnswer || '',
          item.question_id
        ))
      };
    } catch (e) {
      return { question_id: item.question_id, error: 'Failed to generate' };
    }
  }));

  return c.json({ success: true, data: results });
});

// Thuật toán so sánh đơn giản (Có thể nâng cấp lên phoneme level sau)
function calculateAccuracy(s1: string, s2: string): number {
  if (s1 === s2) return 1.0;
  if (!s1 || !s2) return 0.0;

  const len1 = s1.length;
  const len2 = s2.length;
  const matrix = Array.from({ length: len1 + 1 }, () => Array(len2 + 1).fill(0));

  for (let i = 0; i <= len1; i++) matrix[i][0] = i;
  for (let j = 0; j <= len2; j++) matrix[0][j] = j;

  for (let i = 1; i <= len1; i++) {
    for (let j = 1; j <= len2; j++) {
      const cost = s1[i - 1] === s2[j - 1] ? 0 : 1;
      matrix[i][j] = Math.min(
        matrix[i - 1][j] + 1,
        matrix[i][j - 1] + 1,
        matrix[i - 1][j - 1] + cost
      );
    }
  }

  const distance = matrix[len1][len2];
  return Math.max(0, 1 - distance / Math.max(len1, len2));
}

/**
 * GET /api/v1/ai/dictionary-lookup?word=...
 */
aiRouter.get('/dictionary-lookup', async (c) => {
  const word = c.req.query('word')?.trim().toLowerCase();
  if (!word) {
    return c.json({ success: false, message: 'Missing word parameter' }, 400);
  }

  // 1. Dùng Free Dictionary API trước
  try {
    const dictRes = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${encodeURIComponent(word)}`);
    if (dictRes.ok) {
      const data = await dictRes.json() as any[];
      const entry = data[0];
      const phonetic = entry.phonetic || (entry.phonetics && entry.phonetics[0]?.text) || '';
      
      // Lấy definition đầu tiên ưu tiên verb, noun, adj
      let pos = '';
      let defEn = '';
      let exEn = '';
      if (entry.meanings && entry.meanings.length > 0) {
        // Find best meaning
        const bestMeaning = entry.meanings[0];
        pos = bestMeaning.partOfSpeech || '';
        const defObj = bestMeaning.definitions.find((d: any) => d.example) || bestMeaning.definitions[0];
        if (defObj) {
          defEn = defObj.definition || '';
          exEn = defObj.example || '';
        }
      }

      // Dịch sang tiếng Việt bằng Google Translate
      const translate = async (text: string) => {
        if (!text) return '';
        try {
          const res = await fetch(`https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=vi&dt=t&q=${encodeURIComponent(text)}`);
          if (res.ok) {
            const tData = await res.json() as any;
            return tData[0].map((p: any) => p[0]).join('');
          }
        } catch { }
        return '';
      };

      const [defVi, exVi] = await Promise.all([translate(defEn), translate(exEn)]);

      return c.json({
        success: true,
        data: {
          word: entry.word,
          phonetic: phonetic,
          part_of_speech: pos,
          definition: defEn,
          definition_vi: defVi,
          example: exEn,
          example_vi: exVi,
          source: 'dictionary_api'
        }
      });
    }
  } catch (error) {
    console.warn('Dictionary API error:', error);
  }

  // 2. Fallback to Llama 3
  try {
    const prompt = `You are an English-Vietnamese dictionary. Provide details for the word or phrase: "${word}". 
Return ONLY a valid JSON object with EXACTLY these keys:
"word": the word itself,
"phonetic": the IPA phonetic transcription (e.g. /həˈləʊ/),
"part_of_speech": noun, verb, adjective, etc.,
"definition": the English definition,
"definition_vi": the accurate Vietnamese translation of the definition,
"example": a practical English example sentence,
"example_vi": the Vietnamese translation of the example sentence.

Ensure the output is pure JSON without any markdown formatting like \`\`\`json.`;

    const aiRes = await c.env.AI.run(JSON_CHAT_MODEL, {
      messages: [{ role: 'user', content: prompt }],
      response_format: { type: 'json_object' }
    });

    let resultJson = aiRes.response;
    if (resultJson.startsWith('```json')) {
       resultJson = resultJson.replace(/```json/g, '').replace(/```/g, '').trim();
    }
    
    const parsed = JSON.parse(resultJson);
    parsed.source = 'workers_ai';

    return c.json({
      success: true,
      data: parsed
    });
  } catch (error: any) {
    console.error('Llama3 Lookup Error:', error);
    return c.json({ success: false, message: 'AI processing failed' }, 500);
  }
});

export default aiRouter;
